//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeSetting
    {
        public AttributeSetting()
        {
            this.AttributeSettingId = Guid.NewGuid();
            this.BestFieldDetectionSettings = new HashSet<BestFieldDetectionSetting>();
        }
    
        public System.Guid AttributeSettingId { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public string SchemaName { get; set; }
        public string DisplayName { get; set; }
        public string CustomName { get; set; }
        public Nullable<System.Guid> SectionId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public Nullable<bool> ExcludeUpdate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> UseForAutoMerge { get; set; }
    
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<BestFieldDetectionSetting> BestFieldDetectionSettings { get; set; }
        public virtual Session Session { get; set; }
    }
}
