//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoMergeRuleMaster
    {
        public AutoMergeRuleMaster()
        {
            this.EntityAutoMergeRules = new HashSet<EntityAutoMergeRule>();
        }
    
        public System.Guid AutoMergeRuleId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<EntityAutoMergeRule> EntityAutoMergeRules { get; set; }
    }
}
