//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoMergeLogDetail
    {
        public System.Guid AutoMergeLogId { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public System.Guid SessionId { get; set; }
        public string SessionName { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string AppliedAutoMergeRules { get; set; }
        public Nullable<int> RecordsProcessed { get; set; }
        public Nullable<System.Guid> LoggedInUser { get; set; }
        public Nullable<decimal> GroupNo { get; set; }
    
        public virtual AutoMergeLogDetail AutoMergeLogDetails1 { get; set; }
        public virtual AutoMergeLogDetail AutoMergeLogDetail1 { get; set; }
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual User User { get; set; }
        public virtual Session Session { get; set; }
    }
}
