//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestFieldDetPicklistFieldDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BestFieldDetectionSettingsId { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual BestFieldDetectionSetting BestFieldDetectionSetting { get; set; }
    }
}
