//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestFieldDetectionSetting
    {
        public BestFieldDetectionSetting()
        {
            this.BestFieldDetPicklistFieldDetails = new HashSet<BestFieldDetPicklistFieldDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RuleId { get; set; }
        public Nullable<System.Guid> RuleParamId { get; set; }
        public Nullable<int> OrderOfRules { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<System.Guid> AttributeSettingId { get; set; }
        public Nullable<System.Guid> SectionId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual AttributeSetting AttributeSetting { get; set; }
        public virtual BestFieldDetectionRule BestFieldDetectionRule { get; set; }
        public virtual BestFieldsDetRuleParametersMaster BestFieldsDetRuleParametersMaster { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<BestFieldDetPicklistFieldDetail> BestFieldDetPicklistFieldDetails { get; set; }
    }
}
