//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestFieldDetectionRule
    {
        public BestFieldDetectionRule()
        {
            this.BestFieldDetRuleParameters = new HashSet<BestFieldDetRuleParameter>();
            this.BestFieldDetectionSettings = new HashSet<BestFieldDetectionSetting>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BestFieldDetectionRuleTypesId { get; set; }
        public string RuleName { get; set; }
        public string RuleEnum { get; set; }
    
        public virtual BestFieldDetectionRuleType BestFieldDetectionRuleType { get; set; }
        public virtual ICollection<BestFieldDetRuleParameter> BestFieldDetRuleParameters { get; set; }
        public virtual ICollection<BestFieldDetectionSetting> BestFieldDetectionSettings { get; set; }
    }
}
