//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestFieldsDetRuleParametersMaster
    {
        public BestFieldsDetRuleParametersMaster()
        {
            this.BestFieldDetRuleParameters = new HashSet<BestFieldDetRuleParameter>();
            this.BestFieldDetectionSettings = new HashSet<BestFieldDetectionSetting>();
        }
    
        public System.Guid Id { get; set; }
        public string Parameter { get; set; }
        public string ParameterEnum { get; set; }
    
        public virtual ICollection<BestFieldDetRuleParameter> BestFieldDetRuleParameters { get; set; }
        public virtual ICollection<BestFieldDetectionSetting> BestFieldDetectionSettings { get; set; }
    }
}
