//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestRecordDetectionRule
    {
        public BestRecordDetectionRule()
        {
            this.BestRecordDetectionSettings = new HashSet<BestRecordDetectionSetting>();
            this.BestRecordRuleParameters = new HashSet<BestRecordRuleParameter>();
        }
    
        public System.Guid Id { get; set; }
        public string RuleName { get; set; }
        public string RuleEnum { get; set; }
        public Nullable<bool> Account { get; set; }
        public Nullable<bool> Contact { get; set; }
        public Nullable<bool> Lead { get; set; }
    
        public virtual ICollection<BestRecordDetectionSetting> BestRecordDetectionSettings { get; set; }
        public virtual ICollection<BestRecordRuleParameter> BestRecordRuleParameters { get; set; }
    }
}
