//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAutoMergeRule
    {
        public EntityAutoMergeRule()
        {
            this.EntityRuleId = Guid.NewGuid();
            this.SessionAutoMergeRules = new HashSet<SessionAutoMergeRule>();
        }
    
        public System.Guid EntityRuleId { get; set; }
        public Nullable<System.Guid> EntitySettingId { get; set; }
        public Nullable<System.Guid> AutoMergeRuleId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual AutoMergeRuleMaster AutoMergeRuleMaster { get; set; }
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual ICollection<SessionAutoMergeRule> SessionAutoMergeRules { get; set; }
    }
}
