//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRuleDetail
    {
        public System.Guid GroupRuleDetailId { get; set; }
        public System.Guid GroupRuleId { get; set; }
        public string AttributeEnum { get; set; }
        public string AttributeValue { get; set; }
        public string Type { get; set; }
    
        public virtual GroupRule GroupRule { get; set; }
    }
}
