//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRule
    {
        public GroupRule()
        {
            this.GroupRuleId = new Guid();
            this.GroupRuleDetails = new HashSet<GroupRuleDetail>();
        }
    
        public System.Guid GroupRuleId { get; set; }
        public System.Guid GroupId { get; set; }
        public Nullable<System.Guid> RuleId { get; set; }
        public bool IsMaster { get; set; }
        public Nullable<int> Order { get; set; }
        public string Description { get; set; }
    
        public virtual MatchRuleMaster MatchRuleMaster { get; set; }
        public virtual ICollection<GroupRuleDetail> GroupRuleDetails { get; set; }
    }
}
