//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchAttributeSetting
    {
        public System.Guid MatchAttributeSettingId { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public Nullable<System.Guid> MatchGroupId { get; set; }
        public string SchemaName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual MatchGroup MatchGroup { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Session Session { get; set; }
    }
}
