//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRuleDropDownDetail
    {
        public MatchRuleDropDownDetail()
        {
            this.MatchRuleDropDownDetail1 = new HashSet<MatchRuleDropDownDetail>();
        }
    
        public System.Guid DropDownDetailId { get; set; }
        public System.Guid DropDownId { get; set; }
        public string Enum { get; set; }
        public string Value { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    
        public virtual MatchRuleDropDown MatchRuleDropDown { get; set; }
        public virtual ICollection<MatchRuleDropDownDetail> MatchRuleDropDownDetail1 { get; set; }
        public virtual MatchRuleDropDownDetail MatchRuleDropDownDetail2 { get; set; }
    }
}
