//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchKeyMaster
    {
        public MatchKeyMaster()
        {
            this.MatchGroups = new HashSet<MatchGroup>();
            this.SessionGroups = new HashSet<SessionGroup>();
            this.SessionThresholdSettings = new HashSet<SessionThresholdSetting>();
        }
    
        public System.Guid MatchKeyID { get; set; }
        public string MatchKey { get; set; }
        public string Enum { get; set; }
    
        public virtual ICollection<MatchGroup> MatchGroups { get; set; }
        public virtual ICollection<SessionGroup> SessionGroups { get; set; }
        public virtual ICollection<SessionThresholdSetting> SessionThresholdSettings { get; set; }
    }
}
