//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoOfSessionsPerEntityUsage
    {
        public System.Guid PackageId { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public Nullable<int> UsedValue { get; set; }
    }
}
