//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PAM2Entities : DbContext
    {
        public PAM2Entities()
            : base("name=PAM2Entities")
        {
        }

        public PAM2Entities(string strConnString)
            : base("name=PAM2Entities")
        {
            this.Database.Connection.ConnectionString = strConnString;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AutoMergeLogDetail> AutoMergeLogDetails { get; set; }
        public DbSet<AutoMergeRuleMaster> AutoMergeRuleMasters { get; set; }
        public DbSet<CategoryDetail> CategoryDetails { get; set; }
        public DbSet<CategoryMaster> CategoryMasters { get; set; }
        public DbSet<EntityAutoMergeRule> EntityAutoMergeRules { get; set; }
        public DbSet<EntitySetting> EntitySettings { get; set; }
        public DbSet<GroupRule> GroupRules { get; set; }
        public DbSet<GroupRuleDetail> GroupRuleDetails { get; set; }
        public DbSet<InactiveRecordSetting> InactiveRecordSettings { get; set; }
        public DbSet<LanguageMaster> LanguageMasters { get; set; }
        public DbSet<MatchAttributeSetting> MatchAttributeSettings { get; set; }
        public DbSet<MatchGroup> MatchGroups { get; set; }
        public DbSet<MatchGroupMaster> MatchGroupMasters { get; set; }
        public DbSet<MatchKeyMaster> MatchKeyMasters { get; set; }
        public DbSet<MatchRuleDropDown> MatchRuleDropDowns { get; set; }
        public DbSet<MatchRuleDropDownDetail> MatchRuleDropDownDetails { get; set; }
        public DbSet<MatchRuleMaster> MatchRuleMasters { get; set; }
        public DbSet<MemoFieldConfiguration> MemoFieldConfigurations { get; set; }
        public DbSet<PriorityMaster> PriorityMasters { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<SessionAutoMergeRule> SessionAutoMergeRules { get; set; }
        public DbSet<SessionGroup> SessionGroups { get; set; }
        public DbSet<SessionMatchDetail> SessionMatchDetails { get; set; }
        public DbSet<SessionSection> SessionSections { get; set; }
        public DbSet<SmartMergeConfigurationSetting> SmartMergeConfigurationSettings { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<SuppressionHstory> SuppressionHstories { get; set; }
        public DbSet<SuppressionSetting> SuppressionSettings { get; set; }
        public DbSet<ThemeMaster> ThemeMasters { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<NoOfGroupsPerSessionUsage> NoOfGroupsPerSessionUsages { get; set; }
        public DbSet<NoOfSessionsPerEntityUsage> NoOfSessionsPerEntityUsages { get; set; }
        public DbSet<NoOfGroupsPerSessionUsageHistory> NoOfGroupsPerSessionUsageHistories { get; set; }
        public DbSet<NoOfSessionsPerEntityUsageHistory> NoOfSessionsPerEntityUsageHistories { get; set; }
        public DbSet<StatusReasonSetting> StatusReasonSettings { get; set; }
        public DbSet<BestRecordDetectionRule> BestRecordDetectionRules { get; set; }
        public DbSet<BestRecordRuleParameter> BestRecordRuleParameters { get; set; }
        public DbSet<BestRecordRuleParametersMaster> BestRecordRuleParametersMasters { get; set; }
        public DbSet<BestRecordDetectionSetting> BestRecordDetectionSettings { get; set; }
        public DbSet<SessionBestRecordSetting> SessionBestRecordSettings { get; set; }
        public DbSet<BestFieldDetRuleParameter> BestFieldDetRuleParameters { get; set; }
        public DbSet<BestFieldsDetRuleParametersMaster> BestFieldsDetRuleParametersMasters { get; set; }
        public DbSet<BestFieldDetectionRuleType> BestFieldDetectionRuleTypes { get; set; }
        public DbSet<AutoPromoteAndFillLogDetail> AutoPromoteAndFillLogDetails { get; set; }
        public DbSet<BestFieldDetectionRule> BestFieldDetectionRules { get; set; }
        public DbSet<SessionThresholdSetting> SessionThresholdSettings { get; set; }
        public DbSet<AttributeSetting> AttributeSettings { get; set; }
        public DbSet<BestFieldDetectionSetting> BestFieldDetectionSettings { get; set; }
        public DbSet<BestFieldDetPicklistFieldDetail> BestFieldDetPicklistFieldDetails { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<SessionResult> SessionResults { get; set; }
    }
}
