//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleDropDownDetail_NotInUse
    {
        public System.Guid RuleDetailId { get; set; }
        public System.Guid DropDownId { get; set; }
        public string Enum { get; set; }
    }
}
