//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
			this.SectionId = Guid.NewGuid();
            this.SessionSections = new HashSet<SessionSection>();
            this.AttributeSettings = new HashSet<AttributeSetting>();
            this.BestFieldDetectionSettings = new HashSet<BestFieldDetectionSetting>();
        }
    
        public System.Guid SectionId { get; set; }
        public string SectionName { get; set; }
        public int DisplayOrder { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SessionSection> SessionSections { get; set; }
        public virtual ICollection<AttributeSetting> AttributeSettings { get; set; }
        public virtual ICollection<BestFieldDetectionSetting> BestFieldDetectionSettings { get; set; }
    }
}
