//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionAutoMergeRule
    {
        public System.Guid SessionAutoMergeRuleId { get; set; }
        public System.Guid EntityAutoMergeRuleId { get; set; }
        public System.Guid SessionId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual EntityAutoMergeRule EntityAutoMergeRule { get; set; }
        public virtual SessionAutoMergeRule SessionAutoMergeRule1 { get; set; }
        public virtual SessionAutoMergeRule SessionAutoMergeRule2 { get; set; }
        public virtual Session Session { get; set; }
    }
}
