//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionMatchDetail
    {
        public System.Guid SessionMatchId { get; set; }
        public System.Guid SessionId { get; set; }
        public int RecordsFed { get; set; }
        public Nullable<int> DuplicatesFound { get; set; }
        public Nullable<int> ConfirmedResultCount { get; set; }
        public Nullable<int> UnsureResultCount { get; set; }
        public string MatchStatus { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
