//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionResult
    {
        public System.Guid SessionResultId { get; set; }
        public System.Guid SessionId { get; set; }
        public System.Guid RecordId { get; set; }
        public Nullable<bool> ValidGroup { get; set; }
        public decimal GroupNo { get; set; }
        public Nullable<int> GroupRank { get; set; }
        public Nullable<int> MatchScore { get; set; }
        public Nullable<System.DateTime> PunchIn { get; set; }
        public Nullable<System.DateTime> PunchOut { get; set; }
        public Nullable<System.Guid> ReviewStatus { get; set; }
        public Nullable<System.Guid> Reviewer { get; set; }
        public Nullable<System.DateTime> CurentStatusDateTime { get; set; }
        public string EntityHeaderFieldValue { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserNotes { get; set; }
        public Nullable<bool> AutoPromote { get; set; }
        public Nullable<bool> AutoFill { get; set; }
        public Nullable<bool> AutoPromoteFill { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
    }
}
