//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionThresholdSetting
    {
        public System.Guid SessionThresholdId { get; set; }
        public System.Guid SessionId { get; set; }
        public int Threshold1 { get; set; }
        public int Threshold2 { get; set; }
        public Nullable<System.Guid> LanguageId { get; set; }
        public Nullable<bool> IncludeOriginal { get; set; }
        public Nullable<bool> TreatAccountNulls { get; set; }
        public Nullable<bool> TreatNulls { get; set; }
        public Nullable<System.Guid> MatchKeyID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ViewType { get; set; }
        public string ViewName { get; set; }
        public string FetchXML { get; set; }
        public Nullable<bool> ValueToNull { get; set; }
    
        public virtual LanguageMaster LanguageMaster { get; set; }
        public virtual MatchKeyMaster MatchKeyMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Session Session { get; set; }
    }
}
