//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.SessionId = Guid.NewGuid();
            this.AttributeSettings = new HashSet<AttributeSetting>();
            this.AutoMergeLogDetails = new HashSet<AutoMergeLogDetail>();
            this.AutoPromoteAndFillLogDetails = new HashSet<AutoPromoteAndFillLogDetail>();
            this.MatchAttributeSettings = new HashSet<MatchAttributeSetting>();
            this.SessionAutoMergeRules = new HashSet<SessionAutoMergeRule>();
            this.SessionBestRecordSettings = new HashSet<SessionBestRecordSetting>();
            this.SessionGroups = new HashSet<SessionGroup>();
            this.SessionMatchDetails = new HashSet<SessionMatchDetail>();
            this.SessionResults = new HashSet<SessionResult>();
            this.SessionSections = new HashSet<SessionSection>();
            this.SessionThresholdSettings = new HashSet<SessionThresholdSetting>();
        }
    
        public System.Guid SessionId { get; set; }
        public string SessionName { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public Nullable<System.DateTime> RefreshDate { get; set; }
        public Nullable<int> GroupCount { get; set; }
        public Nullable<System.Guid> MergeStatus { get; set; }
        public Nullable<bool> IsAutoMergeInProgress { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string OutputFilePath { get; set; }
        public Nullable<System.Guid> ExecutedBy { get; set; }
        public Nullable<System.DateTime> ExecutedOn { get; set; }
        public Nullable<System.DateTime> ExecutionEnd { get; set; }
        public Nullable<bool> IsAutoPromoteInProgress { get; set; }
        public Nullable<bool> IsAutoFillInProgress { get; set; }
        public Nullable<bool> IsAutoFillAndPromoteInProgress { get; set; }
        public Nullable<bool> IsAutoPromotedAll { get; set; }
        public Nullable<bool> IsAutoFillAll { get; set; }
        public Nullable<bool> IsAutoPromoteFillAll { get; set; }
        public string MatchStatus { get; set; }
    
        public virtual ICollection<AttributeSetting> AttributeSettings { get; set; }
        public virtual ICollection<AutoMergeLogDetail> AutoMergeLogDetails { get; set; }
        public virtual ICollection<AutoPromoteAndFillLogDetail> AutoPromoteAndFillLogDetails { get; set; }
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual ICollection<MatchAttributeSetting> MatchAttributeSettings { get; set; }
        public virtual Session Session1 { get; set; }
        public virtual Session Session2 { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SessionAutoMergeRule> SessionAutoMergeRules { get; set; }
        public virtual ICollection<SessionBestRecordSetting> SessionBestRecordSettings { get; set; }
        public virtual ICollection<SessionGroup> SessionGroups { get; set; }
        public virtual ICollection<SessionMatchDetail> SessionMatchDetails { get; set; }
        public virtual ICollection<SessionResult> SessionResults { get; set; }
        public virtual ICollection<SessionSection> SessionSections { get; set; }
        public virtual ICollection<SessionThresholdSetting> SessionThresholdSettings { get; set; }
    }
}
