//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.SuppressionHstories = new HashSet<SuppressionHstory>();
            this.Sessions = new HashSet<Session>();
            this.SessionResults = new HashSet<SessionResult>();
        }
    
        public System.Guid StatusId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Enum { get; set; }
    
        public virtual ICollection<SuppressionHstory> SuppressionHstories { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<SessionResult> SessionResults { get; set; }
    }
}
