//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppressionHstory
    {
        public System.Guid SuppressionHistoryId { get; set; }
        public string RecordType { get; set; }
        public System.Guid EntitySettingId { get; set; }
        public System.Guid ReviewStatus { get; set; }
        public System.Guid PrimaryId { get; set; }
        public System.Guid SecondaryId { get; set; }
        public string SuppressKey { get; set; }
        public System.Guid ReviewedBy { get; set; }
        public System.Guid SessionId { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EntitySetting EntitySetting { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
