//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectAndMergeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserId = Guid.NewGuid();
            this.AutoMergeLogDetails = new HashSet<AutoMergeLogDetail>();
            this.InactiveRecordSettings = new HashSet<InactiveRecordSetting>();
            this.InactiveRecordSettings1 = new HashSet<InactiveRecordSetting>();
            this.MatchAttributeSettings = new HashSet<MatchAttributeSetting>();
            this.MatchAttributeSettings1 = new HashSet<MatchAttributeSetting>();
            this.MatchGroups = new HashSet<MatchGroup>();
            this.MatchGroups1 = new HashSet<MatchGroup>();
            this.MatchGroupMasters = new HashSet<MatchGroupMaster>();
            this.MatchGroupMasters1 = new HashSet<MatchGroupMaster>();
            this.Sections = new HashSet<Section>();
            this.Sections1 = new HashSet<Section>();
            this.SessionGroups = new HashSet<SessionGroup>();
            this.SessionSections = new HashSet<SessionSection>();
            this.SessionSections1 = new HashSet<SessionSection>();
            this.SmartMergeConfigurationSettings = new HashSet<SmartMergeConfigurationSetting>();
            this.SmartMergeConfigurationSettings1 = new HashSet<SmartMergeConfigurationSetting>();
            this.SuppressionHstories = new HashSet<SuppressionHstory>();
            this.SuppressionHstories1 = new HashSet<SuppressionHstory>();
            this.SuppressionSettings = new HashSet<SuppressionSetting>();
            this.SuppressionSettings1 = new HashSet<SuppressionSetting>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
            this.UserRoles = new HashSet<UserRole>();
            this.AutoPromoteAndFillLogDetails = new HashSet<AutoPromoteAndFillLogDetail>();
            this.SessionThresholdSettings = new HashSet<SessionThresholdSetting>();
            this.SessionThresholdSettings1 = new HashSet<SessionThresholdSetting>();
            this.AttributeSettings = new HashSet<AttributeSetting>();
            this.AttributeSettings1 = new HashSet<AttributeSetting>();
            this.Sessions = new HashSet<Session>();
            this.Sessions1 = new HashSet<Session>();
            this.SessionResults = new HashSet<SessionResult>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> CRMUserId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> SkipDeferred { get; set; }
        public Nullable<int> GridWidth { get; set; }
        public Nullable<int> GridHeight { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> AreTermsAccepted { get; set; }
    
        public virtual ICollection<AutoMergeLogDetail> AutoMergeLogDetails { get; set; }
        public virtual ICollection<InactiveRecordSetting> InactiveRecordSettings { get; set; }
        public virtual ICollection<InactiveRecordSetting> InactiveRecordSettings1 { get; set; }
        public virtual ICollection<MatchAttributeSetting> MatchAttributeSettings { get; set; }
        public virtual ICollection<MatchAttributeSetting> MatchAttributeSettings1 { get; set; }
        public virtual ICollection<MatchGroup> MatchGroups { get; set; }
        public virtual ICollection<MatchGroup> MatchGroups1 { get; set; }
        public virtual ICollection<MatchGroupMaster> MatchGroupMasters { get; set; }
        public virtual ICollection<MatchGroupMaster> MatchGroupMasters1 { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Section> Sections1 { get; set; }
        public virtual ICollection<SessionGroup> SessionGroups { get; set; }
        public virtual ICollection<SessionSection> SessionSections { get; set; }
        public virtual ICollection<SessionSection> SessionSections1 { get; set; }
        public virtual ICollection<SmartMergeConfigurationSetting> SmartMergeConfigurationSettings { get; set; }
        public virtual ICollection<SmartMergeConfigurationSetting> SmartMergeConfigurationSettings1 { get; set; }
        public virtual ICollection<SuppressionHstory> SuppressionHstories { get; set; }
        public virtual ICollection<SuppressionHstory> SuppressionHstories1 { get; set; }
        public virtual ICollection<SuppressionSetting> SuppressionSettings { get; set; }
        public virtual ICollection<SuppressionSetting> SuppressionSettings1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<AutoPromoteAndFillLogDetail> AutoPromoteAndFillLogDetails { get; set; }
        public virtual ICollection<SessionThresholdSetting> SessionThresholdSettings { get; set; }
        public virtual ICollection<SessionThresholdSetting> SessionThresholdSettings1 { get; set; }
        public virtual ICollection<AttributeSetting> AttributeSettings { get; set; }
        public virtual ICollection<AttributeSetting> AttributeSettings1 { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Session> Sessions1 { get; set; }
        public virtual ICollection<SessionResult> SessionResults { get; set; }
    }
}
